import 'package:stylish_ui/model/wishlist_screen_model/wishlist_product_model.dart';

List<WishlistProductModel> wishlistproductlist = [
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product1.jpg',
    title: 'boAt',
    subtext: 'boAt 2025 Launch Airdopes 219 Bluetooth Earbuds',
    price: '1,099',
    rating: 4,
    noofratings: '1,304',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product2.jpg',
    title: 'LAMBOO',
    subtext: 'LAMBOO Men Regular Self Design Spread Collar Casual Shirt',
    price: '399',
    rating: 3.5,
    noofratings: '1,004',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product3.jpg',
    title: 'LAMBOO',
    subtext: "LAMBOO Men's Geometric Triangle Print Shirt",
    price: '350',
    rating: 4.5,
    noofratings: '1,050',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product4.jpg',
    title: 'FEXME',
    subtext:
        'FEXME 5-in-1 Mini Makeup Brush Set with Mirror Blush & Powder Brushes',
    price: '2,050',
    rating: 4,
    noofratings: '2,890',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product5.jpg',
    title: 'Lymio',
    subtext: 'Lymio Jackets Jacket for men Lightweight Outwear Jacket',
    price: '699',
    rating: 2,
    noofratings: '3,567',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product6.jpg',
    title: 'Royal Enfield',
    subtext: "Royal Enfield Men Polyester Riding Jacket Black",
    price: '27,090',
    rating: 4.5,
    noofratings: '6,678',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product10.jpg',
    title: 'GoPro',
    subtext: "GoPro Limited Edition HERO13 Black in Forest Green Camera",
    price: '37,992',
    rating: 5,
    noofratings: '67,980',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product7.jpg',
    title: 'Foxtale',
    subtext: "Foxtale Vitamin C Super Glow Face Wash with Papaya enzyme",
    price: '219',
    rating: 3.5,
    noofratings: '250',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product8.jpg',
    title: 'Rynox',
    subtext: "Rynox Dune Neo Trail Offroad Jacket Offroad Riding Jacket",
    price: "25,999",
    rating: 4.5,
    noofratings: '890',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product9.jpg',
    title: 'GoPro',
    subtext: "GoPro HERO12 Black Powerhouse Bundle Waterproof",
    price: '27,498',
    rating: 4.5,
    noofratings: '32,809',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product9.jpg',
    title: 'GoPro',
    subtext: "GoPro HERO12 Black Powerhouse Bundle Waterproof",
    price: '27,498',
    rating: 4.5,
    noofratings: '32,809',
  ),
  WishlistProductModel(
    imgUrl: 'assets/images/wishlist_images/product9.jpg',
    title: 'GoPro',
    subtext: "GoPro HERO12 Black Powerhouse Bundle Waterproof",
    price: '27,498',
    rating: 4.5,
    noofratings: '32,809',
  ),
];
